In [167]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [168]:
insp_data = pd.read_csv("element_level_inspections.csv")
construction_history = pd.read_csv("construction_history.csv")

C:\Users\Bharat Bojja\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (22,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [169]:
def get_year_str(date_end):
    if int(date_end) > 90:
        return "19" + date_end
    else:
        return "20" + date_end
    
insp_data['ElemInspDate'] = insp_data['ElemInspDate'].map(lambda x: get_year_str(x[6:8]))

In [170]:
insp_data

RecNo     SN  District ElemInspDate  SequenceNbr  SpanGroupKey  \
0       821612993  10002         6         1999           10             1   
1       821612994  10002         6         1999           10             1   
2       821612995  10002         6         1998           11             1   
3       821612996  10002         6         1998           11             1   
4       821612997  10002         6         1998           11             1   
5       821612998  10002         6         1998           11             1   
6       821612999  10002         6         1998           11             1   
7       821613000  10002         6         1998           11             1   
8       821613001  10002         6         1998           12             1   
9       821613002  10002         6         1998           12             1   
10      821613003  10002         6         1998           12             1   
11      821613004  10002         6         1998           12             1   
12      821613005  10002         6         1998           12             1   
13      821613006  10002         6         1998           12             1   
14      821613007  10002         6         1997           13             1   
15      821613008  10002         6         1997           13             1   
16      821613009  10002         6         1997           13             1   
17      821613010  10002         6         1997           13             1   
18      821613011  10002         6         1997           13             1   
19      821613012  10002         6         1997           13             1   
20      821613013  10002         6         1996           14             1   
21      821613014  10002         6         1996           14             1   
22      821613015  10002         6         1996           14             1   
23      821613016  10002         6         1996           14             1   
24      821613017  10002         6         1996           14             1   
25      821613018  10002         6         1996           14             1   
26      821613019  10003         6         2017            1             1   
27      821613020  10003         6         2017            1             1   
28      821613021  10003         6         2017            1             1   
29      821613022  10003         6         2017            1             1   
...           ...    ...       ...          ...          ...           ...   
804311  821621518  20022         9         2008            6             1   
804312  821621519  20022         9         2008            6             1   
804313  821621520  20022         9         2008            6             1   
804314  821621521  20022         9         2008            6             1   
804315  821621522  20022         9         2008            6             1   
804316  821621523  20022         9         2008            6             1   
804317  821621524  20022         9         2008            6             1   
804318  821621525  20022         9         2008            6             1   
804319  821621526  20022         9         2008            6             1   
804320  821621527  20022         9         2008            6             1   
804321  821621528  20022         9         2008            6             1   
804322  821621529  20022         9         2008            6             1   
804323  821621530  20022         9         2008            6             1   
804324  821621531  20022         9         2008            6             1   
804325  821621532  20022         9         2008            6             1   
804326  821621533  20022         9         2008            6             1   
804327  821621534  20022         9         2006            7             1   
804328  821621535  20022         9         2006            7             1   
804329  821621536  20022         9         2006            7             1   
804330  821621537  20022         9

In [171]:
filtered_data = {}
elem_keys = insp_data['ElementKey'].unique()
for envir_num in range(1, 5):
    envir_data = insp_data[insp_data['EnvironmentKey'] == envir_num]
    for elem_key in elem_keys:
        key = str(envir_num) + "." + str(elem_key)
        filtered_data[key] = envir_data[envir_data['ElementKey'] == elem_key]

In [172]:
filtered_data['2.8323']

RecNo     SN  District ElemInspDate  SequenceNbr  SpanGroupKey  \
164     821616270  10052         6         2016            1             1   
168     821616274  10052         6         2014            2             1   
187     821616293  10052         6         2012            3             1   
194     821616300  10052         6         2010            4             1   
216     821617378  10062         6         2001            9             1   
221     821617383  10062         6         1997           10             1   
242     821617404  10062         6         1995           11             1   
247     821617409  10063         6         2017            1             1   
253     821618412  10075         6         2016            1             1   
269     821618428  10075         6         2012            2             1   
275     821618434  10075         6         2008            3             1   
291     821618450  10075         6         2004            4             1   
297     821618456  10075         6         2000            5             1   
453     821622627  20032         9         2017            2             1   
463     821622637  20032         9         2015            3             1   
473     821622647  20032         9         2013            4             1   
483     821622657  20032         9         2011            5             1   
597     821622667  20032         9         2009            6             1   
607     821622677  20032         9         2007            7             1   
617     821622687  20032         9         2005            8             1   
627     821622697  20032         9         2003            9             1   
637     821622707  20032         9         2002           10             1   
647     821622717  20032         9         1998           11             1   
714     821618472  10075         6         1996            6             1   
1103    821616320  10052         6         2008            5             1   
1173    821614223  10016         6         2016            2             1   
1296    821616371  10052         6         2000            9             1   
1303    821616378  10052         6         1999           10             1   
1323    821616398  10052         6         1997           11             1   
1336    821617462  10063         6         2009            5             1   
...           ...    ...       ...          ...          ...           ...   
803013  821637033  60052         3         2003           11             1   
803039  821630327  40015         2         2013            3             1   
803052  821630340  40015         2         2011            4             1   
803063  821630351  40015         2         2009            5             1   
803109  821622578  20031         9         2003            5             1   
803119  821622588  20031         9         2000            6             1   
803129  821622598  20031         9         1998            7             1   
803139  821622608  20031         9         1996            8             1   
803148  821622617  20032         9         2018            1             1   
803527  821636477  60048         3         2007            9             1   
803530  821636480  60048         3         2006           10             1   
803630  821617325  10062         6         2009            5             1   
803635  821617330  10062         6         2007            6             1   
803657  821617352  10062         6         2005            7             1   
803662  821617357  10062         6         2003            8             1   
803905  821631045  50001         6         2004            8             1   
803909  821631049  50001         6         2002            9             1   
803935  821631075  50001         6         2000           10             1   
803939  821631079  50001         6         1998           11             1   
803957  821641128  60114         3

In [ ]:
# key_list = list(filtered_data.keys())
# for key in key_list:
#     SN_list = filtered_data[key]['SN'].unique()
#     filtered_data[key][filtered_data[key]['SN'] == sn_num].drop_duplicates(subset=['ElemInspDate'], keep='last')



In [175]:
def sn_normalize(data):
    sn_freq = data['SN'].value_counts()
    sn_nums = sorted(data['SN'].unique())
    sn_norm = np.zeros(len(sn_nums), dtype=np.int32)
    counter = 0
    acc = 0
    for i in sn_nums:
        val = sn_freq[i]
        sn_norm[counter] += val + acc - 1
        acc += val
        counter += 1
    return sn_norm

print(sn_normalize(filtered_data['1.8323']))

def yearConverter(data):
    sn_norm = sn_normalize(data)
    counter = 0
    for i in sn_norm:
        end_next = (i + 1).item()
        min_val = int(data['ElemInspDate'][counter:end_next].astype(str).min())
        data['ElemInspDate'][counter:end_next] = data['ElemInspDate'][counter:end_next].astype(int) - min_val
        counter = end_next
    return data

print(yearConverter(filtered_data['1.8323']))

[   13    25    36 ..., 16737 16741 16744]
            RecNo     SN  District  ElemInspDate  SequenceNbr  SpanGroupKey  \
0       821612993  10002         6             3           10             1   
3       821612996  10002         6             2           11             1   
12      821613005  10002         6             2           12             1   
15      821613008  10002         6             1           13             1   
24      821613017  10002         6             0           14             1   
27      821613020  10003         6            21            1             1   
35      821613028  10003         6            19            2             1   
37      821613030  10003         6            17            3             1   
45      821613038  10003         6            16            4             1   
47      821613040  10003         6            14            5             1   
116     821615195  10044         6            19            2             1   
120     8

In [176]:
def year_normalize(data):
    year_freq = data['ElemInspDate'].value_counts()
    year_nums = sorted(data['ElemInspDate'].unique())
    year_norm = np.zeros(len(year_nums), dtype=np.int32)
    counter = 0
    acc = 0
    for i in year_nums:
        val = year_freq[i]
        year_norm[counter] += val + acc - 1
        acc += val
        counter += 1
    return year_norm

print(year_normalize(filtered_data['1.8323']))

def get_prob_matrix(data):
#     max_ = int(data['ElemInspDate'].astype(str).max())
    data.sort_values("ElemInspDate", inplace=True)
    counter_list = year_normalize(data)
    matrix = np.zeros(shape=(len(counter_list), 4))

    
#     for i in range(max_ + 1):
#         for j in range(4):
#             elem_perc = data['ElemPercent' + str(j + 1)]
#             if i == 0:
#                 matrix[i][j] = elem_perc[:counter_list[i] + 1].mean() / 100
#             else:
#                 print(i)
#                 matrix[i][j] = elem_perc[counter_list[i - 1] + 1:counter_list[i] + 1].mean() / 100
    runner = 0
    counter = 0
    for i in counter_list:
        end_next = (i + 1).item()
        for j in range(4):
            matrix[counter][j] = data['ElemPercent' + str(j + 1)][runner:end_next].mean()
        runner = end_next
        counter += 1
    return matrix / 100

[ 2272  2930  4234  5019  6088  6779  7710  8378  9182  9741 10392 10975
 11626 12165 12714 13224 13754 14253 14778 15298 15863 16359 16686 16744]


In [177]:
m1 = get_prob_matrix(yearConverter(filtered_data['1.8323']))
print(m1)
print()
m2 = get_prob_matrix(yearConverter(filtered_data['2.8323']))
print(m2)
print()
m3 = get_prob_matrix(yearConverter(filtered_data['3.8323']))
print(m3)
print()
m4 = get_prob_matrix(yearConverter(filtered_data['4.8323']))
print(m4)
print()

[[ 0.61688957  0.32380994  0.05050154  0.00879894]
 [ 0.57978723  0.3343465   0.06990881  0.01595745]
 [ 0.57604294  0.36452454  0.04907975  0.01035276]
 [ 0.58089172  0.35859873  0.05286624  0.00764331]
 [ 0.59471469  0.35126286  0.04934518  0.00467727]
 [ 0.60033285  0.34033285  0.05426918  0.00506512]
 [ 0.66111708  0.28786251  0.04457573  0.00644468]
 [ 0.59904192  0.34332335  0.05389222  0.00374251]
 [ 0.62810945  0.32151741  0.04228856  0.00808458]
 [ 0.6183542   0.31903399  0.05635063  0.00626118]
 [ 0.64400922  0.31221198  0.03840246  0.00537634]
 [ 0.60433962  0.33734134  0.05145798  0.00686106]
 [ 0.59869432  0.34293395  0.05069124  0.00768049]
 [ 0.59925788  0.33395176  0.06307978  0.00371058]
 [ 0.55100182  0.3852459   0.05919854  0.00455373]
 [ 0.53431373  0.39607843  0.06764706  0.00196078]
 [ 0.56288679  0.35645283  0.0759434   0.00471698]
 [ 0.5751503   0.36272545  0.06012024  0.00200401]
 [ 0.54681905  0.39270476  0.05285714  0.00761905]
 [ 0.50192308  0.41201923  0.08

C:\Users\Bharat Bojja\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [178]:
np.savetxt("prob_1_8323.csv", m1, delimiter=",")
np.savetxt("prob_2_8323.csv", m2, delimiter=",")
np.savetxt("prob_3_8323.csv", m3, delimiter=",")
np.savetxt("prob_4_8323.csv", m4, delimiter=",")